
apiVersion: argoproj.io/v1beta1
kind: Application
metadata:
  name: admin
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: admin
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/mihailtudoran/sdl_argo.git
    targetRevision: main
    path: teams/admin/dev
    helm:
      parameters:
      - name: spec.ingress.host
        value: dev.example.com
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
